services:
  python-prod-local:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    container_name: fablabot-prod
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN_FILE=/run/secrets/discord_token
      - GUILD_TOKEN_FILE=/run/secrets/guild_token
      - PERSONAL_ID_FILE=/run/secrets/personal_id
    secrets:
      - discord_token
      - guild_token
      - personal_id
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

secrets:
  discord_token:
    file: ./secrets/discord_token.secret
  guild_token:
    file: ./secrets/guild_token.secret
  personal_id:
    file: ./secrets/personal_id.secret
