services:
  python:
    container_name: fablabot
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/home/BotFabLab

    command: python /home/BotFabLab/main.py
    restart: unless-stopped
