version: "3"
services:
  python:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./src:/home/BotFabLab   # Corrected the space here

    command: python /home/BotFabLab/main.py
    restart: always
