[project]
name = "fablabot"
version = "0.1.0"
description = "General purpose Discord bot for the DeVinci Fablab discord server."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord-py==2.5.2",
    "python-dotenv==1.0.0",
    "selenium==4.8.3",
    "webdriver-manager==3.8.5",
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
where = ["src"]
include = ["fablabot*"]

[project.scripts]
main = "fablabot.main:main"
doc_builder = "fablabot._build_docs:build_docs"


[dependency-groups]
dev = [
    "pdoc>=15.0.3",
    "ruff>=0.12.9",
]

[tool.ruff]
line-length = 128
target-version = "py313"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
    "B",
    "C4",
    "E",
    "F",
    "I",
    "N",
    "PIE",
    "PTH",
    "RET",
    "RUF",
    "SIM",
    "UP",
    "W",
    "D",
]
ignore = ["D105", "E5", "PTH123", "W505"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.pycodestyle]
max-doc-length = 128

[tool.ruff.lint.isort]
force-sort-within-sections = true
