"""Helpers for formation management cog."""

from fablabot.cogs.helpers.constants import EASTER_EGGS, PARIS_TZ, EasterEggTrigger, Emojis, ErrorMessages, RoleNames
from fablabot.cogs.helpers.formation_models import Draft, Formation, PublishedMessage, ReactionEvent
from fablabot.cogs.helpers.formation_notifications import (
    notify_participants_before_formation,
    notify_responsible_before_formation,
    notify_trainer_before_formation,
    send_promotion_dm,
    send_registration_dm,
    send_waitlist_dm,
)
from fablabot.cogs.helpers.formation_rendering import (
    format_current_registrations,
    format_formation_export,
    format_respo_contacts,
    humanize_dt,
    parse_date_time,
    render_message,
)
from fablabot.cogs.helpers.utils import (
    ADMIN_ROLES,
    check_has_role,
    escape_md,
    format_channel_mention,
    format_member_mention,
    format_role_mention,
    get_or_fetch_member,
    is_in_allowed_channel,
    log_request,
    safe_add_roles,
    safe_create_text_channel,
    safe_create_voice_channel,
    safe_delete_channel,
    safe_edit_channel,
    safe_remove_roles,
    send_dm_to_member,
)

__all__ = [
    "ADMIN_ROLES",
    "EASTER_EGGS",
    "PARIS_TZ",
    "Draft",
    "EasterEggTrigger",
    "Emojis",
    "ErrorMessages",
    "Formation",
    "PublishedMessage",
    "ReactionEvent",
    "RoleNames",
    "check_has_role",
    "escape_md",
    "format_channel_mention",
    "format_current_registrations",
    "format_formation_export",
    "format_member_mention",
    "format_respo_contacts",
    "format_role_mention",
    "get_or_fetch_member",
    "humanize_dt",
    "is_in_allowed_channel",
    "log_request",
    "notify_participants_before_formation",
    "notify_responsible_before_formation",
    "notify_trainer_before_formation",
    "parse_date_time",
    "render_message",
    "safe_add_roles",
    "safe_create_text_channel",
    "safe_create_voice_channel",
    "safe_delete_channel",
    "safe_edit_channel",
    "safe_remove_roles",
    "send_dm_to_member",
    "send_promotion_dm",
    "send_registration_dm",
    "send_waitlist_dm",
]
